-- =============================================================================
--  035 — NIGHT REQUESTS: the one thing that may be written while the shop is shut
-- -----------------------------------------------------------------------------
--  Run by hand in Supabase → SQL Editor, AFTER 030 and 031 (it grants to
--  og_vps, and uses schema erp). Safe to run twice: every statement replaces or
--  skips what is already there. No local migration goes with it and it creates
--  no mirrored table, so mirror-lag.js, drift, reconcile and restore do not
--  change.
--
--  WHAT NIGHT MODE IS
--    When the shop laptop is off or out of reach, og-bridge on the VPS serves
--    a small app at shop.ogsports1.com/night (vps/og-bridge/src/night.js). It
--    reads the mirror as og_vps — stock, customers, recent orders — and it may
--    write ONE thing: a REQUEST (a customer, some sizes, delivery or pickup).
--    The request waits here. The laptop collects it the next time it is on
--    (server/lib/requests.js, from Inbox.collect every minute) into a list
--    called "Waiting for the shop", where a PERSON accepts it — it becomes a
--    normal order through the laptop's own order code — or rejects it with a
--    reason. The decision is written back here so the night app can show it.
--    Nothing is applied by itself, and the laptop stays the only writer of
--    shop data.
--
--  WHY A TABLE OF ITS OWN, BESIDE og-track's inbox.items
--    inbox.items is taken, applied and marked done in one pass (a review, a
--    Notify me). A request is DECIDED BY A PERSON, later, and the answer has to
--    travel back: waiting → received → accepted | rejected. That is the shape
--    wip/web-orders gave web.orders, so this table is GENERIC on purpose
--    (source 'night' | 'web'): the website's orders can arrive here later and
--    land in the same list. og-track's table and functions are not touched.
--
--  WHAT og_vps GAINS — AND WHAT IT DOES NOT
--    EXECUTE on erp.request_submit and erp.requests_list. That is all.
--    NO table privilege anywhere (not even USAGE on schema inbox), so it is
--    still SELECT-only on the shop's tables. Its sessions stay read-only by
--    default (030); og-bridge opens `BEGIN READ WRITE` for the submit call and
--    for nothing else — an INSERT inside a SECURITY DEFINER function still
--    fails in a read-only transaction, which is the point of 030's default.
--    The last block of this file FAILS THE WHOLE FILE if og_vps can write to
--    any relation, or read inbox.requests directly.
--
--  WHAT IT CREATES
--    inbox.requests                        the requests (schema inbox: not exposed)
--    erp.request_submit(user, op, req)     og_vps       — a night user asks
--    erp.requests_list(user, limit)        og_vps       — what became of them
--    public.requests_take(lineage, limit)  service_role — the laptop collects
--    public.requests_mark(lineage, items)  service_role — received / accepted / rejected
--    inbox.req_*                           private helpers, no role may call them
--
--  LIMITS (a leaked night account must not be able to bury the shop)
--    20 lines, 20 of one size, 60 pieces per request · 5 undecided per phone ·
--    30 per night user per hour · 1,000 undecided in all · 8 KB per payload.
--
--  AFTER RUNNING IT
--    Do NOT add `inbox` or `erp` to Exposed schemas. The last two queries show
--    what og_vps can do; the guard above them has already refused a wrong one.
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS inbox;
REVOKE ALL ON SCHEMA inbox FROM PUBLIC;
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated', 'service_role', 'og_vps'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON SCHEMA inbox FROM %I', r);
    END IF;
  END LOOP;
END $$;

-- -----------------------------------------------------------------------------
--  The table. ref is what people read ("N-0042"); op is the requester's own
--  idempotency key, so a form sent twice on a slow line is one request.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inbox.requests (
  id             bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref            text        NOT NULL,
  source         text        NOT NULL,
  op             text        NOT NULL,
  payload        jsonb       NOT NULL,
  phone_digits   text        NOT NULL,
  by_user        text,
  revision       integer     NOT NULL DEFAULT 1,
  state          text        NOT NULL DEFAULT 'waiting',
  state_code     text,
  state_note     text,
  sale_id        text,
  taken_by       text,
  taken_revision integer,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  decided_at     timestamptz,
  CONSTRAINT requests_ref_unique    UNIQUE (ref),
  CONSTRAINT requests_op_unique     UNIQUE (source, op),
  CONSTRAINT requests_ref_shape     CHECK (ref ~ '^[A-Za-z0-9][A-Za-z0-9_-]{2,39}$'),
  CONSTRAINT requests_source_check  CHECK (source IN ('night', 'web')),
  CONSTRAINT requests_state_check   CHECK (state IN ('waiting', 'received', 'accepted', 'rejected')),
  CONSTRAINT requests_code_shape    CHECK (state_code IS NULL OR state_code ~ '^[a-z_]{1,40}$'),
  CONSTRAINT requests_note_len      CHECK (state_note IS NULL OR char_length(state_note) <= 200),
  CONSTRAINT requests_sale_len      CHECK (sale_id IS NULL OR char_length(sale_id) <= 40),
  CONSTRAINT requests_payload_size  CHECK (octet_length(payload::text) <= 8192)
);

COMMENT ON TABLE inbox.requests IS
  'Night requests (and, later, website orders) waiting for the shop laptop to decide (035). Not a mirrored table; never add it to the POS sync, reconcile or restore lists.';

ALTER TABLE inbox.requests ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE inbox.requests FROM PUBLIC;
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated', 'service_role', 'og_vps'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON TABLE inbox.requests FROM %I', r);
      EXECUTE format('REVOKE ALL ON SEQUENCE inbox.requests_id_seq FROM %I', r);
    END IF;
  END LOOP;
END $$;

CREATE INDEX IF NOT EXISTS requests_open_idx  ON inbox.requests (id) WHERE state IN ('waiting', 'received');
CREATE INDEX IF NOT EXISTS requests_phone_idx ON inbox.requests (phone_digits) WHERE state IN ('waiting', 'received');
CREATE INDEX IF NOT EXISTS requests_user_idx  ON inbox.requests (by_user, created_at);

-- -----------------------------------------------------------------------------
--  Private helpers. Nobody has USAGE on schema inbox and EXECUTE is revoked
--  below, so only the four doors (which run as the owner) can use them.
-- -----------------------------------------------------------------------------

-- Is this the database that owns the mirror? The first word of sync_state row
-- 'lineage' — the question og-track's inbox.is_owner asks, restated so this
-- file does not depend on og-track's.
CREATE OR REPLACE FUNCTION inbox.req_owner(p_lineage text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT coalesce(
    p_lineage <> '' AND p_lineage = (
      SELECT nullif(split_part(st.note, ' ', 1), '')
        FROM public.sync_state st
       WHERE st.id = 'lineage'
    ),
    false
  );
$$;

CREATE OR REPLACE FUNCTION inbox.req_no(p_code text, p_field text DEFAULT NULL)
RETURNS jsonb
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE WHEN p_field IS NULL
              THEN jsonb_build_object('ok', false, 'code', p_code)
              ELSE jsonb_build_object('ok', false, 'code', p_code, 'field', p_field) END;
$$;

-- A string field of an object, or NULL when it is absent or not a string.
CREATE OR REPLACE FUNCTION inbox.req_str(p_obj jsonb, p_key text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT CASE WHEN jsonb_typeof(p_obj -> p_key) = 'string' THEN p_obj ->> p_key END;
$$;

-- One line of text: every control character (newlines included) becomes a
-- space, runs of spaces collapse, trimmed; empty is NULL.
CREATE OR REPLACE FUNCTION inbox.req_line(p_text text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT nullif(btrim(regexp_replace(regexp_replace(coalesce(p_text, ''), '[[:cntrl:]]', ' ', 'g'), ' {2,}', ' ', 'g')), '');
$$;

-- A few lines of text (an address, a note): \r dropped, every other control
-- character but the newline dropped, at most one blank line in a row, trimmed;
-- empty is NULL. The tracking page's review comment is tidied the same way.
CREATE OR REPLACE FUNCTION inbox.req_block(p_text text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = ''
AS $$
  SELECT nullif(btrim(
           regexp_replace(
             regexp_replace(replace(coalesce(p_text, ''), E'\r', ''), E'[\\x01-\\x09\\x0B-\\x1F\\x7F]', '', 'g'),
             E'\n{3,}', E'\n\n', 'g'),
           E' \n'), '');
$$;

-- -----------------------------------------------------------------------------
--  erp.request_submit — a night user asks. og_vps only, in a READ WRITE
--  transaction (og-bridge's mirror.submit). The payload is BUILT HERE: the
--  product names, sizes and colours come from the mirror, never from the
--  caller, and the laptop re-resolves every SKU and prices it from its own
--  table anyway.
--  Returns {ok:true, ref, state, at[, replayed]} or {ok:false, code[, field][, sku]}.
--  Codes: bad_user, bad_op, op_taken, unsupported, too_big, bad_name,
--  bad_phone, bad_customer, bad_items, unknown_sku, bad_delivery, bad_city,
--  bad_address, bad_note, too_many_phone, too_many_user, full.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION erp.request_submit(p_user text, p_op text, p_request jsonb)
RETURNS jsonb
LANGUAGE plpgsql
VOLATILE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_row     inbox.requests%ROWTYPE;
  v_cust    jsonb;
  v_name    text;
  v_phone   text;
  v_digits  text;
  v_cid     bigint;
  v_items   jsonb;
  v_e       jsonb;
  v_sku     text;
  v_qty     integer;
  v_total   integer := 0;
  v_seen    text[] := '{}';
  v_lines   jsonb := '[]'::jsonb;
  v_var     record;
  v_dlv     jsonb;
  v_method  text;
  v_city    text;
  v_address text;
  v_country text;
  v_note    text;
  v_payload jsonb;
  v_id      bigint;
  v_ref     text;
BEGIN
  IF p_user IS NULL OR p_user !~ '^[a-z0-9._-]{2,32}$' THEN RETURN inbox.req_no('bad_user'); END IF;
  IF p_op IS NULL OR p_op !~ '^[A-Za-z0-9_-]{16,64}$' THEN RETURN inbox.req_no('bad_op'); END IF;

  -- The same form sent twice (a double tap, a retry on a slow line) is one
  -- request. The op is minted per draft by og-bridge, so the same op from
  -- another user can only be a mistake — refused rather than answered.
  SELECT * INTO v_row FROM inbox.requests r WHERE r.source = 'night' AND r.op = p_op;
  IF FOUND THEN
    IF v_row.by_user IS DISTINCT FROM p_user THEN RETURN inbox.req_no('op_taken'); END IF;
    RETURN jsonb_build_object('ok', true, 'ref', v_row.ref, 'state', v_row.state,
                              'at', v_row.created_at, 'replayed', true);
  END IF;

  IF p_request IS NULL OR jsonb_typeof(p_request) <> 'object' THEN RETURN inbox.req_no('unsupported'); END IF;
  IF octet_length(p_request::text) > 8192 THEN RETURN inbox.req_no('too_big'); END IF;
  IF (p_request -> 'v') IS DISTINCT FROM '1'::jsonb THEN RETURN inbox.req_no('unsupported', 'v'); END IF;

  -- The customer: a name and a phone. An id is only a hint — the mirror
  -- customer the night user picked — and the laptop uses it only while that
  -- customer's phone still matches.
  v_cust := p_request -> 'customer';
  IF jsonb_typeof(v_cust) IS DISTINCT FROM 'object' THEN RETURN inbox.req_no('bad_name', 'customer.name'); END IF;
  v_name := inbox.req_line(inbox.req_str(v_cust, 'name'));
  IF v_name IS NULL OR char_length(v_name) NOT BETWEEN 2 AND 80 THEN
    RETURN inbox.req_no('bad_name', 'customer.name');
  END IF;
  v_phone := inbox.req_line(inbox.req_str(v_cust, 'phone'));
  v_digits := regexp_replace(coalesce(v_phone, ''), '[^0-9]', '', 'g');
  IF v_phone IS NULL OR char_length(v_phone) > 40 OR char_length(v_digits) NOT BETWEEN 7 AND 15 THEN
    RETURN inbox.req_no('bad_phone', 'customer.phone');
  END IF;
  IF v_cust ? 'id' AND jsonb_typeof(v_cust -> 'id') <> 'null' THEN
    IF jsonb_typeof(v_cust -> 'id') <> 'number' OR (v_cust ->> 'id') !~ '^[1-9][0-9]{0,11}$' THEN
      RETURN inbox.req_no('bad_customer', 'customer.id');
    END IF;
    v_cid := (v_cust ->> 'id')::bigint;
  END IF;

  -- The sizes. Named by SKU; everything else about them is read here.
  v_items := p_request -> 'items';
  IF jsonb_typeof(v_items) IS DISTINCT FROM 'array' OR jsonb_array_length(v_items) NOT BETWEEN 1 AND 20 THEN
    RETURN inbox.req_no('bad_items', 'items');
  END IF;
  FOR v_e IN SELECT e.value FROM jsonb_array_elements(v_items) AS e(value) LOOP
    IF jsonb_typeof(v_e) <> 'object' THEN RETURN inbox.req_no('bad_items', 'items'); END IF;
    v_sku := inbox.req_str(v_e, 'sku');
    IF v_sku IS NULL OR v_sku !~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$' OR v_sku = ANY (v_seen) THEN
      RETURN inbox.req_no('bad_items', 'items');
    END IF;
    v_seen := v_seen || v_sku;
    IF jsonb_typeof(v_e -> 'qty') <> 'number' OR (v_e ->> 'qty') !~ '^[0-9]{1,2}$' THEN
      RETURN inbox.req_no('bad_items', 'items');
    END IF;
    v_qty := (v_e ->> 'qty')::integer;
    IF v_qty NOT BETWEEN 1 AND 20 THEN RETURN inbox.req_no('bad_items', 'items'); END IF;
    v_total := v_total + v_qty;
    IF v_total > 60 THEN RETURN inbox.req_no('bad_items', 'items'); END IF;

    SELECT v.sku, v.size, p.name,
           CASE WHEN (SELECT count(*) FROM public.product_colours c2 WHERE c2.product_id = p.id) > 1
                THEN c.name_en END AS colour,
           CASE WHEN (SELECT count(*) FROM public.product_colours c2 WHERE c2.product_id = p.id) > 1
                THEN c.name_ar END AS colour_ar
      INTO v_var
      FROM public.variants v
      JOIN public.products p ON p.id = v.product_id
      LEFT JOIN public.product_colours c ON c.id = v.colour_id
     WHERE v.sku = v_sku AND NOT p.hidden AND NOT p.demo;
    IF NOT FOUND THEN
      RETURN jsonb_build_object('ok', false, 'code', 'unknown_sku', 'field', 'items', 'sku', v_sku);
    END IF;
    v_lines := v_lines || jsonb_build_array(jsonb_strip_nulls(jsonb_build_object(
      'sku', v_var.sku, 'qty', v_qty, 'name', v_var.name, 'size', v_var.size,
      'colour', v_var.colour, 'colourAr', v_var.colour_ar)));
  END LOOP;

  -- Delivery or pickup. The generic set (driver, office, courier, abroad) is
  -- the website's; at night the person on the phone says only which of the
  -- two, and the shop chooses how it travels when it accepts.
  v_dlv := p_request -> 'delivery';
  IF jsonb_typeof(v_dlv) IS DISTINCT FROM 'object' THEN RETURN inbox.req_no('bad_delivery', 'delivery'); END IF;
  v_method := inbox.req_str(v_dlv, 'method');
  IF v_method IS NULL OR v_method NOT IN ('pickup', 'delivery') THEN
    RETURN inbox.req_no('bad_delivery', 'delivery.method');
  END IF;
  IF v_method <> 'pickup' THEN
    v_city := inbox.req_line(inbox.req_str(v_dlv, 'city'));
    IF v_city IS NULL OR char_length(v_city) NOT BETWEEN 2 AND 80 THEN
      RETURN inbox.req_no('bad_city', 'delivery.city');
    END IF;
    v_address := inbox.req_block(inbox.req_str(v_dlv, 'address'));
    IF v_address IS NULL OR char_length(v_address) NOT BETWEEN 3 AND 300 THEN
      RETURN inbox.req_no('bad_address', 'delivery.address');
    END IF;
    v_country := inbox.req_str(v_dlv, 'country');
    IF v_country IS NOT NULL AND v_country !~ '^[A-Z]{2}$' THEN
      RETURN inbox.req_no('bad_delivery', 'delivery.country');
    END IF;
  END IF;

  IF p_request ? 'note' AND jsonb_typeof(p_request -> 'note') NOT IN ('string', 'null') THEN
    RETURN inbox.req_no('bad_note', 'note');
  END IF;
  v_note := inbox.req_block(inbox.req_str(p_request, 'note'));
  IF v_note IS NOT NULL AND char_length(v_note) > 500 THEN RETURN inbox.req_no('bad_note', 'note'); END IF;

  -- The limits.
  IF (SELECT count(*) FROM inbox.requests r
       WHERE r.phone_digits = v_digits AND r.state IN ('waiting', 'received')) >= 5 THEN
    RETURN inbox.req_no('too_many_phone', 'customer.phone');
  END IF;
  IF (SELECT count(*) FROM inbox.requests r
       WHERE r.source = 'night' AND r.by_user = p_user AND r.created_at > now() - interval '1 hour') >= 30 THEN
    RETURN inbox.req_no('too_many_user');
  END IF;
  IF (SELECT count(*) FROM inbox.requests r WHERE r.state IN ('waiting', 'received')) >= 1000 THEN
    RETURN inbox.req_no('full');
  END IF;

  v_payload := jsonb_build_object(
    'v', 1,
    'customer', jsonb_strip_nulls(jsonb_build_object('name', v_name, 'phone', v_phone, 'id', v_cid)),
    'items', v_lines,
    'delivery', jsonb_strip_nulls(jsonb_build_object('method', v_method, 'city', v_city,
                                                     'address', v_address, 'country', v_country)),
    'note', v_note
  );

  v_id := nextval(pg_get_serial_sequence('inbox.requests', 'id'));
  v_ref := 'N-' || lpad(v_id::text, 4, '0');
  INSERT INTO inbox.requests (id, ref, source, op, payload, phone_digits, by_user)
  VALUES (v_id, v_ref, 'night', p_op, v_payload, v_digits, p_user)
  RETURNING * INTO v_row;

  RETURN jsonb_build_object('ok', true, 'ref', v_row.ref, 'state', v_row.state, 'at', v_row.created_at);
EXCEPTION WHEN unique_violation THEN
  -- The same op at the same instant, from two tabs: the second reads the first.
  SELECT * INTO v_row FROM inbox.requests r WHERE r.source = 'night' AND r.op = p_op;
  IF FOUND AND v_row.by_user = p_user THEN
    RETURN jsonb_build_object('ok', true, 'ref', v_row.ref, 'state', v_row.state,
                              'at', v_row.created_at, 'replayed', true);
  END IF;
  RETURN inbox.req_no('op_taken');
END;
$$;

COMMENT ON FUNCTION erp.request_submit(text, text, jsonb) IS
  'Night mode (035): a night user asks for an order. og_vps only, in a READ WRITE transaction. Returns {ok, ref, state, at} or {ok:false, code}.';

-- -----------------------------------------------------------------------------
--  erp.requests_list — what became of them, newest first. One user's own
--  (a staff account), or everybody's when p_user is NULL (the owner and the
--  manager; og-bridge decides which from the night account's role).
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION erp.requests_list(p_user text, p_limit integer DEFAULT 50)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  SELECT jsonb_build_object('ok', true, 'items', coalesce(jsonb_agg(x.j ORDER BY x.id DESC), '[]'::jsonb))
    FROM (SELECT r.id,
                 jsonb_build_object('ref', r.ref, 'source', r.source, 'state', r.state,
                                    'code', r.state_code, 'note', r.state_note, 'saleId', r.sale_id,
                                    'byUser', r.by_user, 'at', r.created_at, 'decidedAt', r.decided_at,
                                    'payload', r.payload) AS j
            FROM inbox.requests r
           WHERE p_user IS NULL OR r.by_user = p_user
           ORDER BY r.id DESC
           LIMIT least(greatest(coalesce(p_limit, 50), 1), 100)) x;
$$;

COMMENT ON FUNCTION erp.requests_list(text, integer) IS
  'Night mode (035): the requests a night user made (or all of them for NULL), newest first. og_vps only.';

-- -----------------------------------------------------------------------------
--  public.requests_take — the laptop collects, oldest first: anything not yet
--  taken by THIS lineage at its latest revision, and anything another laptop
--  took and never decided — so a request still waiting for a yes follows the
--  shop when it moves laptops. Decided requests never come back. Reads only;
--  requests_mark says 'received'.
--  Codes: not_owner.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.requests_take(p_lineage text, p_limit integer DEFAULT 20)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_items jsonb;
BEGIN
  IF NOT inbox.req_owner(p_lineage) THEN RETURN inbox.req_no('not_owner'); END IF;

  SELECT coalesce(jsonb_agg(jsonb_build_object(
           'ref', o.ref, 'source', o.source, 'revision', o.revision, 'state', o.state,
           'payload', o.payload, 'byUser', o.by_user, 'createdAt', o.created_at) ORDER BY o.id), '[]'::jsonb)
    INTO v_items
    FROM (SELECT *
            FROM inbox.requests w
           WHERE w.state IN ('waiting', 'received')
             AND (w.taken_by IS DISTINCT FROM p_lineage OR w.taken_revision IS DISTINCT FROM w.revision)
           ORDER BY w.id
           LIMIT least(greatest(coalesce(p_limit, 20), 1), 50)) o;

  RETURN jsonb_build_object('ok', true, 'items', v_items);
END;
$$;

COMMENT ON FUNCTION public.requests_take(text, integer) IS
  'Night mode (035): the shop laptop collects requests. Service key and the mirror''s lineage id only.';

-- -----------------------------------------------------------------------------
--  public.requests_mark — the laptop says what it did with each one:
--    {ref, state:'received', revision}          it is in the "Waiting for the shop" list
--    {ref, state:'accepted', saleId}            a real order now
--    {ref, state:'rejected', code, note}        the shop said no, and why
--  A DECISION IS FINAL. Nothing moves an accepted request to rejected or back,
--  an accepted one never changes its invoice, and 'received' never undoes a
--  decision. Each item is answered with the state the cloud now holds, so the
--  laptop knows its report landed. At most 50 per call.
--  Codes: not_owner, bad_items.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.requests_mark(p_lineage text, p_items jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_e      jsonb;
  v_ref    text;
  v_state  text;
  v_rev    integer;
  v_sale   text;
  v_code   text;
  v_note   text;
  v_row    inbox.requests%ROWTYPE;
  v_out    jsonb := '[]'::jsonb;
  v_marked integer := 0;
  v_n      integer;
BEGIN
  IF NOT inbox.req_owner(p_lineage) THEN RETURN inbox.req_no('not_owner'); END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) > 50 THEN
    RETURN inbox.req_no('bad_items');
  END IF;

  FOR v_e IN SELECT e.value FROM jsonb_array_elements(p_items) AS e(value) LOOP
    IF jsonb_typeof(v_e) IS DISTINCT FROM 'object' THEN CONTINUE; END IF;
    v_ref := inbox.req_str(v_e, 'ref');
    v_state := inbox.req_str(v_e, 'state');
    IF v_ref IS NULL OR v_state IS NULL THEN CONTINUE; END IF;
    v_n := 0;

    IF v_state = 'received' THEN
      v_rev := CASE WHEN jsonb_typeof(v_e -> 'revision') = 'number' AND (v_e ->> 'revision') ~ '^[0-9]{1,9}$'
                    THEN (v_e ->> 'revision')::integer END;
      UPDATE inbox.requests o
         SET state = 'received',
             taken_by = p_lineage,
             taken_revision = CASE WHEN v_rev IS NOT NULL AND v_rev <= o.revision THEN v_rev ELSE o.taken_revision END,
             updated_at = now()
       WHERE o.ref = v_ref AND o.state IN ('waiting', 'received');
      GET DIAGNOSTICS v_n = ROW_COUNT;

    ELSIF v_state = 'accepted' THEN
      v_sale := inbox.req_str(v_e, 'saleId');
      IF v_sale IS NOT NULL AND v_sale ~ '^[A-Za-z0-9][A-Za-z0-9_-]{0,39}$' THEN
        UPDATE inbox.requests o
           SET state = 'accepted', sale_id = v_sale, state_code = NULL, state_note = NULL,
               taken_by = p_lineage, decided_at = coalesce(o.decided_at, now()), updated_at = now()
         WHERE o.ref = v_ref AND o.state IN ('waiting', 'received');
        GET DIAGNOSTICS v_n = ROW_COUNT;
      END IF;

    ELSIF v_state = 'rejected' THEN
      v_code := coalesce(inbox.req_str(v_e, 'code'), 'other');
      IF v_code !~ '^[a-z_]{1,40}$' THEN v_code := 'other'; END IF;
      v_note := left(inbox.req_block(inbox.req_str(v_e, 'note')), 200);
      UPDATE inbox.requests o
         SET state = 'rejected', state_code = v_code, state_note = v_note,
             taken_by = p_lineage, decided_at = coalesce(o.decided_at, now()), updated_at = now()
       WHERE o.ref = v_ref AND o.state IN ('waiting', 'received');
      GET DIAGNOSTICS v_n = ROW_COUNT;
    END IF;

    v_marked := v_marked + v_n;
    SELECT * INTO v_row FROM inbox.requests o WHERE o.ref = v_ref;
    IF FOUND THEN
      v_out := v_out || jsonb_build_array(jsonb_build_object(
        'ref', v_row.ref, 'state', v_row.state, 'saleId', v_row.sale_id, 'code', v_row.state_code));
    ELSE
      v_out := v_out || jsonb_build_array(jsonb_build_object('ref', v_ref, 'state', NULL));
    END IF;
  END LOOP;

  RETURN jsonb_build_object('ok', true, 'marked', v_marked, 'items', v_out);
END;
$$;

COMMENT ON FUNCTION public.requests_mark(text, jsonb) IS
  'Night mode (035): the shop laptop reports received / accepted / rejected. A decision is final. Service key and the mirror''s lineage id only.';

-- -----------------------------------------------------------------------------
--  Who may call what. Postgres (and Supabase's default privileges on public)
--  let other roles execute a new function, so every one is shut first and then
--  opened to exactly ONE role.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  f text;
  r text;
BEGIN
  FOREACH f IN ARRAY ARRAY[
    'inbox.req_owner(text)', 'inbox.req_no(text, text)', 'inbox.req_str(jsonb, text)',
    'inbox.req_line(text)', 'inbox.req_block(text)',
    'erp.request_submit(text, text, jsonb)', 'erp.requests_list(text, integer)',
    'public.requests_take(text, integer)', 'public.requests_mark(text, jsonb)'
  ] LOOP
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC', f);
    FOREACH r IN ARRAY ARRAY['anon', 'authenticated', 'service_role', 'og_vps'] LOOP
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
        EXECUTE format('REVOKE ALL ON FUNCTION %s FROM %I', f, r);
      END IF;
    END LOOP;
  END LOOP;
END $$;

GRANT EXECUTE ON FUNCTION erp.request_submit(text, text, jsonb)  TO og_vps;
GRANT EXECUTE ON FUNCTION erp.requests_list(text, integer)       TO og_vps;
GRANT EXECUTE ON FUNCTION public.requests_take(text, integer)    TO service_role;
GRANT EXECUTE ON FUNCTION public.requests_mark(text, jsonb)      TO service_role;

-- -----------------------------------------------------------------------------
--  THE GUARD. og_vps is still SELECT-only on every table, and cannot reach
--  inbox.requests except through the two functions above. Anything else fails
--  this whole file, so a wrong grant made elsewhere is found here, not later.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
  bad text;
BEGIN
  SELECT string_agg(format('%I.%I %s', n.nspname, c.relname, p.priv), ', ' ORDER BY n.nspname, c.relname, p.priv)
    INTO bad
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
   CROSS JOIN (VALUES ('INSERT'), ('UPDATE'), ('DELETE'), ('TRUNCATE')) AS p(priv)
   WHERE c.relkind IN ('r', 'p', 'v', 'm', 'f')
     AND n.nspname NOT IN ('pg_catalog', 'information_schema')
     AND n.nspname NOT LIKE 'pg\_%'
     AND (has_table_privilege('og_vps', c.oid, p.priv)
          OR (p.priv IN ('INSERT', 'UPDATE') AND has_any_column_privilege('og_vps', c.oid, p.priv)));
  IF bad IS NOT NULL THEN
    RAISE EXCEPTION 'og_vps can write, and must not: %', bad;
  END IF;
  IF has_table_privilege('og_vps', 'inbox.requests', 'SELECT') OR has_schema_privilege('og_vps', 'inbox', 'USAGE') THEN
    RAISE EXCEPTION 'og_vps can reach inbox.requests directly, and must not';
  END IF;
  IF has_function_privilege('og_vps', 'public.requests_take(text, integer)', 'EXECUTE')
     OR has_function_privilege('og_vps', 'public.requests_mark(text, jsonb)', 'EXECUTE') THEN
    RAISE EXCEPTION 'og_vps can collect or decide requests, and must not';
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';

-- What each role can call now. Expect og_vps on the two erp functions,
-- service_role on the two public ones, and nobody on inbox.req_*.
SELECT n.nspname || '.' || p.proname AS function,
       has_function_privilege('og_vps', p.oid, 'EXECUTE')       AS og_vps,
       has_function_privilege('service_role', p.oid, 'EXECUTE') AS service_role,
       has_function_privilege('anon', p.oid, 'EXECUTE')         AS anon,
       has_function_privilege('authenticated', p.oid, 'EXECUTE') AS authenticated
  FROM pg_proc p
  JOIN pg_namespace n ON n.oid = p.pronamespace
 WHERE (n.nspname = 'erp' AND p.proname LIKE 'request%')
    OR (n.nspname = 'inbox' AND p.proname LIKE 'req\_%')
    OR (n.nspname = 'public' AND p.proname IN ('requests_take', 'requests_mark'))
 ORDER BY 1;

-- og_vps's table privileges: SELECT only (and users as (id, name) columns).
SELECT table_schema, table_name, string_agg(DISTINCT privilege_type, ', ') AS privileges
  FROM information_schema.role_table_grants
 WHERE grantee = 'og_vps'
 GROUP BY table_schema, table_name
 ORDER BY 1, 2;
