-- =============================================================================
--  CATCH-UP.sql — every mirror schema file this project has not had run yet
-- -----------------------------------------------------------------------------
--  GENERATED. Do not edit this file; edit the numbered files it is built from
--  and regenerate. Built 2026-09-02 against wsuqoippcxcwoszcgagc, where
--  npm run supabase:drift reported 008, 009, 010 and 011 all outstanding;
--  012 (2026-09-02, the Yalla Wear line) appended the same day.
--
--  Paste the whole thing into the Supabase SQL editor and run it once.
--  Every statement is CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS,
--  so running it twice, or on a project already partly caught up, is safe.
--
--  AFTERWARDS, in this order:
--    cd server && npm run supabase:drift      -- should go green
--    cd server && npm run supabase:reconcile  -- REQUIRED, see below
--    cd server && npm run supabase:check      -- confirms the data as well
--
--  The reconcile is not optional. The sync pushed sections and customers with
--  the missing columns DROPPED, and its cursor has already moved past those
--  rows — no rewind will ever look at them again. The columns exist after this
--  file but stay NULL in the mirror until the reconcile refills them.
-- =============================================================================


-- #############################################################################
-- ##  008_rooms.sql
-- #############################################################################

-- =============================================================================
--  Mirror schema for rooms and rack placement.
--  Run this in the Supabase SQL editor, like 002 through 007.
-- -----------------------------------------------------------------------------
--  Matches server/migrations/026_rooms.sql column for column.
--
--  Until it is run, supabase-sync.js pushes sections WITHOUT the three new
--  columns (fallbackDrop) and says so by name, and `rooms` is skipped by the
--  layout guard — a day of sales still mirrors. Afterwards, run
--    npm run supabase:reconcile
--  because the sync's cursor has already moved past any section whose
--  placement was dropped, and no rewind will ever look there again.
-- =============================================================================

CREATE TABLE IF NOT EXISTS rooms (
  --  BIGINT, never BIGSERIAL: a sequence of its own would invent different
  --  ids on the second sync and every sections.room_id would point at the
  --  wrong room. Same rule as sections and shelves in 006.
  id          BIGINT PRIMARY KEY,
  wh_id       TEXT NOT NULL,
  name        TEXT NOT NULL,
  sort_index  INTEGER NOT NULL DEFAULT 0,
  width_cm    INTEGER,
  depth_cm    INTEGER,
  height_cm   INTEGER,
  created_at  TIMESTAMPTZ NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL
);

--  No REFERENCES rooms(id) on sections.room_id, even though SQLite has one:
--  a batch of upserts arrives in one call with no ordering guarantee inside
--  it, and a real foreign key rejects the whole batch when a rack lands
--  before its room. No CHECK either — 006 explains what a constraint on the
--  mirror once cost.
ALTER TABLE sections ADD COLUMN IF NOT EXISTS room_id  BIGINT;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS wall     TEXT;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS wall_pos INTEGER;
CREATE INDEX IF NOT EXISTS idx_sections_room ON sections (room_id);

ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;


-- #############################################################################
-- ##  009_gift_receipt.sql
-- #############################################################################

-- =============================================================================
--  Mirror schema for gift receipts.
--  Run this in the Supabase SQL editor, like 002 through 008.
-- -----------------------------------------------------------------------------
--  Matches server/migrations/027_gift_receipt.sql. The three config rows that
--  migration seeds (receipt.gift_exchange_hours and the two policy texts) need
--  nothing here: config is a Mirror-shape table, pushed whole on every run.
--
--  What does need a home is the one column: which kind of paper a print
--  attempt was, 'sale' or 'gift'. A gift slip carries no prices, so it is the
--  one worth being able to trace back to whoever put it on paper.
--
--  Until this is run, supabase-sync.js's print history block is rejected on
--  the column, says so by name, and leaves the maxid cursor where it was — the
--  rows are retried on every run and land the moment the column exists.
--  Nothing to reconcile afterwards.
-- =============================================================================

--  Nullable, no DEFAULT and no CHECK, for the reasons 027 gives: rows from
--  before the distinction genuinely predate it, and a constraint on the mirror
--  is a way to reject a whole batch over one row (see 006).
ALTER TABLE print_log ADD COLUMN IF NOT EXISTS kind TEXT;


-- #############################################################################
-- ##  010_loyalty_and_wants.sql
-- #############################################################################

-- =============================================================================
--  010 — the stamp cards, and what people asked for
-- -----------------------------------------------------------------------------
--  RUN THIS BY HAND in the Supabase SQL editor, like 002–009 before it.
--
--  Until it is run, `npm run supabase:sync` names these two tables and pushes
--  everything else — a day's sales must not stop being mirrored over a table
--  nobody has created yet.
--
--  WHY THESE TWO MATTER MORE THAN THEY LOOK. Almost everything else in this
--  mirror is recoverable from something: a stock figure from the movement log,
--  an open debt from the sale and its payments, a stamp COUNT from the sales it
--  was derived from. These two are not.
--
--    * a redemption is the record that the shop GAVE somebody something. If
--      this row is lost, the stamps it consumed come back — the count is
--      derived as earned-minus-used (server/lib/loyalty.js) — and the customer
--      is holding a card the shop has already honoured.
--    * a want is somebody telling the shop what to order. Nothing else in the
--      database remembers that a person asked for a 44 and left without one.
--
--  Local migrations: 031_loyalty_stamps.sql and 032_job_customer_and_wants.sql.
-- =============================================================================


-- -----------------------------------------------------------------------------
--  loyalty_redemptions  —  APPEND-ONLY on the sync side
-- -----------------------------------------------------------------------------
--  Written once and never edited, so supabase-sync pushes it with the
--  highest-id cursor (syncAppendOnly) rather than by replaying change_log.
--
--  required_then is the load-bearing column and the reason this table exists
--  at all: it is the rule that was in force at that moment, frozen, exactly as
--  sales.fx_rate is. Change the rule from 10 to 8 next year and last year's
--  redemptions must keep meaning what they meant.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS loyalty_redemptions (
  id            BIGINT PRIMARY KEY,
  customer_id   BIGINT,
  at            TEXT NOT NULL,
  user_id       BIGINT,
  stamps_used   INTEGER NOT NULL,
  required_then INTEGER NOT NULL,
  note          TEXT,
  created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS loyalty_redemptions_customer
  ON loyalty_redemptions (customer_id, at);


-- -----------------------------------------------------------------------------
--  wants  —  CURSOR shape, because a want is EDITED
-- -----------------------------------------------------------------------------
--  Deliberately not append-only. A want is written when somebody asks for a
--  size the shop has not got, and UPDATED when the shop comes back to them
--  (closed_at, closed_note). A highest-id cursor would push the row once, on
--  the day it was created, and never notice it being answered — so the mirror
--  would keep saying somebody is still waiting for a pair they collected in
--  March.
--
--  That is why it replays change_log instead, and why both write paths in
--  server/lib/wants.js call logChange — record() as 'insert', close() as
--  'update'. Verified before this file was written; a write that skips
--  logChange is not a missing audit line, it is a row that exists on the shop's
--  machine and nowhere else.
--
--  No foreign keys, matching the rest of this mirror (see 001's header): a
--  restore reads tables in dependency order, and a hard FK here would make an
--  out-of-order push fail rather than simply arrive early.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS wants (
  id          BIGINT PRIMARY KEY,
  customer_id BIGINT NOT NULL,
  product_id  BIGINT,
  variant_sku TEXT,
  size        TEXT,
  source      TEXT NOT NULL DEFAULT 'scan',
  user_id     BIGINT,
  at          TEXT NOT NULL,
  closed_at   TEXT,
  closed_note TEXT
);

CREATE INDEX IF NOT EXISTS wants_customer ON wants (customer_id, at);
CREATE INDEX IF NOT EXISTS wants_open     ON wants (product_id, size) WHERE closed_at IS NULL;


-- -----------------------------------------------------------------------------
--  print_jobs.customer_id  (local migration 032)
-- -----------------------------------------------------------------------------
--  Added here rather than in its own file because it arrives with the same
--  local migration as `wants`. print_jobs is pushed inside the partner guard,
--  which retries on every run — so until this column exists the print board
--  simply mirrors late, it does not lose anything.
-- -----------------------------------------------------------------------------

ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS customer_id BIGINT;

-- -----------------------------------------------------------------------------
--  ROW LEVEL SECURITY
-- -----------------------------------------------------------------------------
--  On, with no policies, exactly as 001 sets it for every mirrored table and
--  every file since has repeated for its own. This file was the one that did
--  not, which was an oversight and not a decision.
--
--  RLS on with no policy means: the service key (which bypasses RLS) still
--  reads and writes, and NOTHING ELSE CAN. That is the whole security model of
--  this mirror — there is no per-user authorisation here to get right, because
--  no user ever reaches it. The shop's own permission matrix lives in SQLite
--  and is enforced by requirePerm() on the server.
--
--  It matters more for these two than for most. `wants` says which customer
--  asked for which pair, and `loyalty_redemptions` says what each customer has
--  claimed — both are the shop's customer list joined to their behaviour,
--  which is the one category of data the FORBIDDEN rules in server/lib/auth.js
--  refuse even to the print partner.
-- -----------------------------------------------------------------------------

ALTER TABLE loyalty_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE wants               ENABLE ROW LEVEL SECURITY;


-- #############################################################################
-- ##  011_credit_and_merge.sql
-- #############################################################################

-- =============================================================================
--  011 — the credit rules, and where a merged customer went
-- -----------------------------------------------------------------------------
--  RUN THIS BY HAND in the Supabase SQL editor, like 002–010 before it.
--
--  These three columns arrived with local migration 033_credit_and_collection
--  and this file was missed at the time — `npm run supabase:check` caught it:
--
--      ✗ customers   missing in Supabase: credit_limit, no_credit, merged_into
--
--  `customers` is pushed in the CORE loop, which is NOT inside a guard, and it
--  is fetched with SELECT * — so on a mirror without these columns PostgREST
--  rejects the whole batch and the shop's customer list stops mirroring
--  entirely. Exactly the sales.shift_id and stock.shelf_id situation described
--  in 006. Until this is run, every customer write waits.
--
--  WHAT THEY MEAN, because a restore has to put them back meaning the same
--  thing:
--
--    credit_limit  IN USD MINOR UNITS (cents), nullable. NULL is "no limit
--                  set"; 0 is "no credit at all". Two different instructions,
--                  which is why the column is nullable rather than DEFAULT 0 —
--                  a restore that turned NULL into 0 would silently stop every
--                  customer's credit.
--
--                  USD and not lira on purpose: a limit written in lira decays
--                  as the currency moves, so a ceiling set last year quietly
--                  stops being one. What is owed is compared against it by
--                  converting each open debt at ITS OWN frozen fx_rate.
--
--    no_credit     0/1. The owner having already decided about this person.
--                  The limit warns; this refuses.
--
--    merged_into   the surviving customer's id, when this record was merged
--                  into another. The loser is ARCHIVED with this pointer and
--                  never deleted — deleting takes the audit trail with it and
--                  leaves every invoice that named the row pointing at nobody.
--
--  No foreign key on merged_into, matching the rest of this mirror (001's
--  header says why): a restore reads rows in dependency order, and a hard FK
--  here would reject a row that merely arrived before the customer it points
--  at rather than letting it land.
-- =============================================================================

ALTER TABLE customers ADD COLUMN IF NOT EXISTS credit_limit BIGINT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS no_credit    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS merged_into  BIGINT;

CREATE INDEX IF NOT EXISTS customers_merged_into
  ON customers (merged_into) WHERE merged_into IS NOT NULL;



-- #############################################################################
-- ##  012_partner_link.sql
-- #############################################################################

-- =============================================================================
--  012 — the line to Yalla Wear: job source, payment handshake, reviews
-- -----------------------------------------------------------------------------
--  RUN THIS BY HAND in the Supabase SQL editor, like 002–011 before it.
--  Matches server/migrations/035_partner_link.sql column for column, EXCEPT
--  partner_events, which is deliberately absent — see the bottom of this file.
--
--  Until it is run, supabase-sync.js pushes print_jobs without `source` and
--  partner_invoice_payments without the three confirmation columns, saying
--  so by name on every run (lib/mirror-lag.js). AFTERWARDS run
--    npm run supabase:reconcile
--  because the sync's cursor has already moved past every row it pushed one
--  column short, and no rewind will ever look there again. Until the
--  reconcile runs, a restore from this mirror hands back a shop where every
--  payment is unconfirmed and every job says "manual".
--
--    print_jobs.source              'till' | 'manual' | 'web' — where the
--                                   job was raised.
--
--    partner_invoice_payments       a payment is now a handshake: one side
--      .recorded_by_side            records it ('og' | 'yalla'), the OTHER
--      .confirmed_at / .confirmed_by  confirms it. Only confirmed money counts
--                                   against the invoice. Rows that predate
--                                   this are stamped confirmed at their own
--                                   time by the local migration.
--
--    job_reviews                    one per finished job: the shop's rating
--                                   out of five and what it said. Cursor
--                                   shape, replayed from change_log.
--
--  NOT HERE: partner_events. That table is the Telegram OUTBOX — delivery
--  state, not shop data. A restored shop that re-sent three months of "order
--  accepted" messages to two phones would be a bug, not a recovery, so the
--  queue lives on the shop machine only and is never mirrored.
--
--  Row level security on, no policies, like every table since 001: the
--  service key works and nothing else does.
-- =============================================================================

ALTER TABLE print_jobs ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual';

ALTER TABLE partner_invoice_payments ADD COLUMN IF NOT EXISTS recorded_by_side TEXT NOT NULL DEFAULT 'og';
ALTER TABLE partner_invoice_payments ADD COLUMN IF NOT EXISTS confirmed_at     TEXT;
ALTER TABLE partner_invoice_payments ADD COLUMN IF NOT EXISTS confirmed_by     BIGINT;

CREATE TABLE IF NOT EXISTS job_reviews (
  job_id     TEXT PRIMARY KEY,
  rating     INTEGER NOT NULL,
  feedback   TEXT,
  user_id    BIGINT,
  at         TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
ALTER TABLE job_reviews ENABLE ROW LEVEL SECURITY;
