-- =============================================================================
--  The partner half — print jobs, the line to Yalla Wear, and the money
--  around it. Plus the two shop-side lists that had never had tables either:
--  suppliers and employees.
-- -----------------------------------------------------------------------------
--  Everything here already existed on screen. It was generated by js/data.js
--  on every page load, which meant the Yalla Wear portal — a whole second
--  company's working day — recorded nothing. A job moved to "printing" and
--  moved back on refresh.
--
--  Shapes follow what the frontend already draws, so the screens do not have
--  to be rewritten around a new model. Where the seed carried a derived
--  value it is NOT stored: a kit job's qty, cost and size breakdown come from
--  its lines, never the other way round, so a line and its total cannot
--  disagree. Only bulk jobs carry their own qty.
--
--  Money follows the rule the rest of the schema follows: integer minor units
--  plus a currency code, never a float.
--
--  employees is deliberately NOT users. A login is a way into the system; an
--  employee is somebody on the payroll. The shop has staff who never sign in
--  and logins (the partner) who are not staff. They are linked where both
--  exist, and neither owns the other.
-- =============================================================================

-- ---------------------------------------------------------------- suppliers
CREATE TABLE IF NOT EXISTS suppliers (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  name            TEXT    NOT NULL,
  contact         TEXT,
  category        TEXT,
  currency        TEXT    NOT NULL DEFAULT 'SYP' REFERENCES currencies(code),
  outstanding     INTEGER NOT NULL DEFAULT 0,
  total_purchased INTEGER NOT NULL DEFAULT 0,
  due_date        TEXT,
  last_payment    TEXT,
  archived        INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0,1)),
  created_at      TEXT    NOT NULL,
  updated_at      TEXT    NOT NULL
);

-- ---------------------------------------------------------------- employees
CREATE TABLE IF NOT EXISTS employees (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id      INTEGER REFERENCES users(id),   -- null: on the payroll, no login
  name         TEXT    NOT NULL,
  role         TEXT    NOT NULL,
  currency     TEXT    NOT NULL DEFAULT 'SYP' REFERENCES currencies(code),
  salary       INTEGER NOT NULL DEFAULT 0,
  next_payment TEXT,
  since        TEXT,
  phone        TEXT,
  archived     INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0,1)),
  created_at   TEXT    NOT NULL,
  updated_at   TEXT    NOT NULL
);

-- -------------------------------------------------------------------- clubs
--  The jersey catalogue a kit line points at. Both languages, because a kit
--  sheet is read on the shop floor in Arabic and by the printer in English.
CREATE TABLE IF NOT EXISTS clubs (
  code       TEXT PRIMARY KEY,
  name       TEXT NOT NULL,
  name_ar    TEXT,
  archived   INTEGER NOT NULL DEFAULT 0 CHECK (archived IN (0,1)),
  created_at TEXT NOT NULL
);

-- --------------------------------------------------------------- print jobs
--  id is the human reference ('P-1043') because it is what everyone says out
--  loud, writes on the bag and quotes down the phone. The next one is derived
--  from the highest that exists rather than a counter, so it cannot drift
--  behind the data the way the label counter once did.
CREATE TABLE IF NOT EXISTS print_jobs (
  id         TEXT PRIMARY KEY,
  customer   TEXT    NOT NULL,
  phone      TEXT,
  design     TEXT    NOT NULL,
  kind       TEXT    NOT NULL DEFAULT 'bulk'   CHECK (kind IN ('bulk','kit')),
  priority   TEXT    NOT NULL DEFAULT 'normal' CHECK (priority IN ('normal','urgent')),
  stage      TEXT    NOT NULL DEFAULT 'design'
             CHECK (stage IN ('design','sent','printing','delivery','done')),
  qty        INTEGER NOT NULL DEFAULT 0,   -- bulk only; a kit's comes from its lines
  currency   TEXT    NOT NULL DEFAULT 'SYP' REFERENCES currencies(code),
  price      INTEGER NOT NULL DEFAULT 0,   -- what the customer pays
  cost       INTEGER,                      -- what Yalla Wear charges; null = not agreed
  deadline   TEXT,
  sale_id    TEXT    REFERENCES sales(id), -- set when the till raised it

  --  The order envelope. "Sent to print" is not something the shop can
  --  assert on its own — it means the printer took the job — so the stage
  --  cannot pass 'sent' until Yalla Wear has accepted. Kept on the job
  --  rather than in its own table because there is exactly one order per
  --  job and it has no life without it.
  order_state        TEXT NOT NULL DEFAULT 'draft'
                     CHECK (order_state IN ('draft','pending','accepted','declined')),
  order_sent_at      TEXT,
  order_responded_at TEXT,
  order_promised_at  TEXT,
  order_note         TEXT,

  created_at TEXT    NOT NULL,
  updated_at TEXT    NOT NULL,
  created_by INTEGER REFERENCES users(id)
);

--  One shirt on a kit sheet. print_name null means TO BE CONFIRMED, which is
--  a real state the shop lives in — an order is taken before the squad is
--  settled — and the reason a kit job cannot be finished while any line is
--  still blank.
CREATE TABLE IF NOT EXISTS print_job_lines (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id     TEXT    NOT NULL REFERENCES print_jobs(id) ON DELETE CASCADE,
  club_code  TEXT    REFERENCES clubs(code),
  print_name TEXT,
  number     INTEGER,
  size       TEXT,
  qty        INTEGER NOT NULL DEFAULT 1 CHECK (qty > 0),
  --  What the PRINTER charges for this shirt, not what the customer pays.
  --  Named unit_cost rather than price for two reasons: the job above
  --  already has a price meaning the opposite side of the margin, and
  --  scrubCost strips it from a response by name, so a cashier who can see
  --  the board still cannot read what the shop makes on every shirt.
  unit_cost  INTEGER NOT NULL DEFAULT 0
);

--  When each step happened, not just where the job sits now. The delivery
--  tracker and every "how late are we" question are answered from here.
CREATE TABLE IF NOT EXISTS print_job_stages (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id  TEXT    NOT NULL REFERENCES print_jobs(id) ON DELETE CASCADE,
  stage   TEXT    NOT NULL,
  at      TEXT    NOT NULL,
  by_side TEXT    CHECK (by_side IN ('og','yalla')),
  user_id INTEGER REFERENCES users(id)
);

-- ------------------------------------------------------------- the invoices
CREATE TABLE IF NOT EXISTS partner_invoices (
  id         TEXT PRIMARY KEY,            -- 'YW-2026-011'
  issued     TEXT NOT NULL,
  due        TEXT NOT NULL,
  note       TEXT,
  currency   TEXT NOT NULL DEFAULT 'SYP' REFERENCES currencies(code),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

--  An invoice covers jobs; a job can appear on only one. The composite key
--  says both.
CREATE TABLE IF NOT EXISTS partner_invoice_refs (
  invoice_id TEXT NOT NULL REFERENCES partner_invoices(id) ON DELETE CASCADE,
  job_id     TEXT NOT NULL REFERENCES print_jobs(id),
  PRIMARY KEY (invoice_id, job_id)
);

--  Part payments are the norm, not the exception, so an invoice is never
--  "paid" as a flag — it is the sum of what has been received against it.
CREATE TABLE IF NOT EXISTS partner_invoice_payments (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  invoice_id TEXT    NOT NULL REFERENCES partner_invoices(id) ON DELETE CASCADE,
  at         TEXT    NOT NULL,
  amount     INTEGER NOT NULL CHECK (amount > 0),
  method     TEXT    NOT NULL,
  user_id    INTEGER REFERENCES users(id)
);

-- ------------------------------------------------------ the two-way message
--  One table read from both portals, which is the whole mechanism: there is
--  no copy and no second source, so a message posted on one side is simply
--  there on the other. read_og and read_yl are tracked separately — reading a
--  thread in one portal must not silently clear the other side's badge — and
--  a sender has by definition already read their own message.
--
--  A message hangs off a job or an invoice, never both and never neither.
CREATE TABLE IF NOT EXISTS job_messages (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id     TEXT    REFERENCES print_jobs(id)      ON DELETE CASCADE,
  invoice_id TEXT    REFERENCES partner_invoices(id) ON DELETE CASCADE,
  from_side  TEXT    NOT NULL CHECK (from_side IN ('og','yalla')),
  kind       TEXT    NOT NULL,
  reason     TEXT,
  body       TEXT    NOT NULL,
  at         TEXT    NOT NULL,
  read_og    INTEGER NOT NULL DEFAULT 0 CHECK (read_og IN (0,1)),
  read_yl    INTEGER NOT NULL DEFAULT 0 CHECK (read_yl IN (0,1)),
  user_id    INTEGER REFERENCES users(id),
  CHECK ((job_id IS NOT NULL) <> (invoice_id IS NOT NULL))
);

-- --------------------------------------------------------- what was sent out
--  A log of messages handed to WhatsApp. The shop's proof that a customer was
--  told, which is worth having the day somebody says they never were.
CREATE TABLE IF NOT EXISTS wa_messages (
  id       INTEGER PRIMARY KEY AUTOINCREMENT,
  at       TEXT    NOT NULL,
  phone    TEXT    NOT NULL,
  body     TEXT    NOT NULL,
  kind     TEXT,
  ref_type TEXT,
  ref_id   TEXT,
  user_id  INTEGER REFERENCES users(id)
);

-- ------------------------------------------------------------------ indexes
CREATE INDEX IF NOT EXISTS idx_job_lines_job    ON print_job_lines(job_id);
CREATE INDEX IF NOT EXISTS idx_job_stages_job   ON print_job_stages(job_id);
CREATE INDEX IF NOT EXISTS idx_msg_job          ON job_messages(job_id);
CREATE INDEX IF NOT EXISTS idx_msg_invoice      ON job_messages(invoice_id);
CREATE INDEX IF NOT EXISTS idx_jobs_stage       ON print_jobs(stage);
CREATE INDEX IF NOT EXISTS idx_inv_refs_job     ON partner_invoice_refs(job_id);
CREATE INDEX IF NOT EXISTS idx_inv_pay_invoice  ON partner_invoice_payments(invoice_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_live   ON suppliers(archived);
CREATE INDEX IF NOT EXISTS idx_employees_live   ON employees(archived);

-- ------------------------------------------------------------ seed: clubs
--  The nine the shop actually prints, lifted from the list the frontend has
--  been drawing all along so a kit sheet reads the same before and after the
--  screens started asking the server. Reference data, not demo data: these
--  are real shirts on a real rail, and a kit line has nothing to point at
--  without them.
INSERT OR IGNORE INTO clubs (code, name, name_ar, created_at) VALUES
  ('rma',  'Real Madrid',                   'ريال مدريد',              datetime('now')),
  ('rmal', 'Real Madrid · Limited Edition', 'ريال مدريد · إصدار محدود', datetime('now')),
  ('bay',  'Bayern Munich',                 'بايرن ميونخ',              datetime('now')),
  ('bar',  'Barcelona 26/27 · Fan Edition', 'برشلونة · نسخة الجماهير',  datetime('now')),
  ('int',  'Inter Milan',                   'إنتر ميلان',               datetime('now')),
  ('fra',  'France',                        'فرنسا',                    datetime('now')),
  ('syr',  'Syria',                         'سوريا',                    datetime('now')),
  ('syrg', 'Syria · Green',                 'سوريا · الأخضر',           datetime('now')),
  ('syrw', 'Syria · White',                 'سوريا · الأبيض',           datetime('now'));
